### PR TITLE
Added Demux

### PR DESCRIPTION
**Pull request by LuisWittrock**
returns data input as a vector which has the data value at index specified by "sel"

### CODE REVIEW

**Comment by yvkrishna** [comment]
@Matschbirne2003, the parameters for demux are not integers, it would be boolean. Also, the select line is a vector containing binary values. for example, sel would be [1,0,1] which means 5. So we need to convert the array containing binaries to integer. 

Anyway one of member is working on it.

**Comment by yvkrishna** [comment]
Thanks for your contribution, I would create new issues, If you like to work on the project you can try for their solutions

**Comment by LuisWittrock** [comment]
> @Matschbirne2003, the parameters for demux are not integers, it would be boolean. Also, the select line is a vector containing binary values. for example, sel would be [1,0,1] which means 5. So we need to convert the array containing binaries to integer. 
> 
> Anyway one of member is working on it.

Oh im sorry my bad. Was my first ever pull request and I fucked it up xD. I'll be careful next time

**Comment by yvkrishna** [comment]
> > @Matschbirne2003, the parameters for demux are not integers, it would be boolean. Also, the select line is a vector containing binary values. for example, sel would be [1,0,1] which means 5. So we need to convert the array containing binaries to integer.
> > Anyway one of member is working on it.
> 
> Oh im sorry my bad. Was my first ever pull request and I fucked it up xD. I'll be careful next time

no problem. You can work on other issues as well

**Pull request closed without merging**
